### ISSUE TITLE
Deploying Datacenter router cloudformation template throws null error

### ISSUE THREAD

**Issue by pabloredo** [geseib/awsnetworkshop#10]
The following error is thrown when deploying datacenter router template for the TGW workshop (awsnetworkshop/resources/templates/2.tgw-csr.yaml):

[/Mappings/RegionMap/ap-northeast-3/SRXAMI] 'null' values are not allowed in templates

Nulls are not allowed for AMI value on ap-northeast-2. Fixed issue by simply replacing null for empty string "".

**Comment by maransel** [comment]
@pabloredo  I'm having the exact same issue now. Can you please elaborate on where you replaced the null value for an empty string ""? I don't have access to the code itself.

**Comment by geseib** [comment]
Great spot. I need to make sure to add that steps when updating.
