### ISSUE TITLE
Cisco router config syntax issue

### ISSUE THREAD

**Issue by givenand** [geseib/awsnetworkshop#22]
On this [step](https://networking.aworkshop.io/40-connect/40-cisco/60-extra-ecmp.html) of the guide:

p-10-4-0-17# config t router bgp 65001 **address-family-ipv4** maximum-paths 8 end

The correct syntax is address-family ipv4 (no hyphen)

**Comment by geseib** [comment]
made the correction. Thanks @givenand.
