### ISSUE TITLE
Search function leads to non-resolvable domain

### ISSUE THREAD

**Issue by mbk-ok** [geseib/awsnetworkshop#29]
In the below screenshot, you can see that I am attempting to search for content, and when I click on any of the destinations, I lead to a destination that isn't resolvable.

![Screen Shot 2021-05-12 at 5 28 30 PM](https://user-images.githubusercontent.com/20977419/118053283-da37b300-b349-11eb-8905-238eda28e4fd.png)

**Comment by geseib** [comment]
looks like it references a dev env. needs to point to correct baseURL. Addressed in fa0367ecfa401e841b68ba01022b6fcfed80e522
