### ISSUE TITLE
Multi-account is crossing references.

### ISSUE THREAD

**Issue by gmagella-ca** [geseib/awsnetworkshop#3]
Hey! Thanks for putting this together, this is very helpful.

I was trying this workshop by myself, and on the multi-account part, I didn't had any resources on the second account (I was not pairing with a someone), so it became clear to me that there might be some confusion on the multi-account set-up.

To make it a bit less confusing, let me set some ground ideas:

User 1 (myself)
- Account 1 (mine)
User 2 (By workshop buddy)
- Account 2 (my buddy's account).

As the two account were mine, on my run, and I had not built anything on the second account... I though I should share the resolver rules as well with account 2, so I did and everything worked as expected (steps to associate the shared rules with the NP3 VPC are not there, I'll put a pull request). 

Thinking that someone might pair, they might end-up associating their NP3 VPC with the resolver rules of Account 2, therefore resolving name on their buddy datacenter, and not theirs. You know what I'm saying?

Same thing goes for the Route Association steps, while following the steps, User 1 would be on Account 2, and the TGW route tables present there, are for User 1 Transit Gateway.  if the association happens there, NP3 for user A will be actually associating with Resources of USER B and messing everything up. Do I understand it correctly?

I'm writing the share resolver rules and an extra page about testing NP3 access to all resources on NP1, 2 and DC1 and I'll put a pull request, but I thought I'd ask about this confusion I'm seeing.

**Comment by geseib** [comment]
great points. I will test with the DNSrefactor branch and look to pull into master

**Comment by geseib** [comment]
ok, i think we still have some work to do, as I read your changes in website/content/60-MultiAccount/60-CrossAccount Attach.md, I read it as you are directing the VPC attachment to happen from the TGW account (Account 1) when it actually happens from Account 2.
I wonder if using terms like hub and spoke account would make sense here.

**Comment by gmagella-ca** [comment]
You're right. I jumped the gun on where to tell the user to switch to the account that owns the TGW (Hub account). The Association with the route-table on TGW and the Propagations have to be on the original account and it wasn't too clear to me.

**Comment by geseib** [comment]
Issue, is more with instructions. Should work fine
