### ISSUE TITLE
Please update the cloudformation template to reflect new amis

### ISSUE THREAD

**Issue by aajolly** [geseib/awsnetworkshop#7]
While trying this workshop and on step --> https://networking.awsworkshops.io/40-connect/40-cisco/30-create-transit.html

I was unable to get the stack working as the Cisco AMIs have been updated on Aug-21-2019. The stack would fail as it won't have ec2:RunInstance permissions on the referenced ami. I had to manually update the template to reflect new ami-id for the region I was deploying this in.

**Comment by geseib** [comment]
yeah, it looks like juniper needs updating as well. and the juniper now
seems to work better with the c5 and require ec2-user as the login instead
of root. I will update the cloudformation with the new AMIs and update the
juniper instructions tomorrow. Thanks for digging into it. Anything need to
change on the Cisco side besides the AMIs?

**Comment by geseib** [comment]
ok. i took a quick pass at it. check it out
